import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { Sidebar } from "@/components/sidebar/sidebar";
import { sidebarConfig } from "@/configs/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
            <div className="flex flex-1 h-screen px-4 py-2">
              <Sidebar.Container>
                <Sidebar.Header className="px-8 py-6">
                  <p className="text-xl font-bold text-primary-500">CHALLENGERZ</p>
                </Sidebar.Header>
                <Sidebar.Items items={sidebarConfig.items} />
              </Sidebar.Container>

              <main className="flex-1 overflow-y-auto">
                {children}
              </main>
            </div>
        </Providers>
      </body>
    </html>
  );
}