import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { Sidebar } from "@/components/sidebar/sidebar";
import { sidebarConfig } from "@/configs/sidebar";
import Image from "next/image";
import Link from "next/link";
import ThemeSwitcher from "@/components/theme-switcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-1 h-screen">
            <Sidebar.Container>
              <Sidebar.Header className="p-8">
                <Link href="/">
                  <Image src="/logo_horizontal.svg" alt="logo horizontal" width={200} height={200} />
                </Link>
              </Sidebar.Header>
              <Sidebar.Items items={sidebarConfig.items} />
              <Sidebar.Footer className="p-8">
                <ThemeSwitcher/>
              </Sidebar.Footer>
            </Sidebar.Container>

            <main className="flex flex-col flex-1 overflow-y-auto">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}