import type { Metadata } from "next";
import "@/app/globals.css";
import PageWrapper from "./page-wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function StepsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div suppressHydrationWarning className="flex flex-1 min-h-screen justify-center">
            <div className="w-1/2 bg-paper m-4 rounded-xl flex flex-col bg-white dark:bg-[#12141A]">
                <PageWrapper>
                    {children}
                </PageWrapper>
            </div>
        </div>
    );
}
